[package]
name = "zodiac"
version = "0.1.0"
authors = ["Callym <hi@callym.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
vsop87 = "2.0.3"
