[package]
name = "zodiac"
version = "0.1.0"
authors = ["Callym <hi@callym.com>"]

[dependencies]
serde = "1.0.21"
serde_derive = "1.0.21"
chrono = { version = "0.4.0", features = ["serde"] }
vsop87 = "2.0.3"
